terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[c28a-s2:18522] *** Process received signal ***
[c28a-s2:18522] Signal: Aborted (6)
[c28a-s2:18522] Signal code:  (-6)
[c28a-s2:18522] [ 0] /lib64/libpthread.so.0[0x3888c0f7e0]
[c28a-s2:18522] [ 1] /lib64/libc.so.6(gsignal+0x35)[0x38888325e5]
[c28a-s2:18522] [ 2] /lib64/libc.so.6(abort+0x175)[0x3888833dc5]
[c28a-s2:18522] [ 3] /apps/compilers/gcc/5.2.0/lib64/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x15d)[0x2b10e0777b6d]
[c28a-s2:18522] [ 4] /apps/compilers/gcc/5.2.0/lib64/libstdc++.so.6(+0x8cbb6)[0x2b10e0775bb6]
[c28a-s2:18522] [ 5] /apps/compilers/gcc/5.2.0/lib64/libstdc++.so.6(+0x8cc01)[0x2b10e0775c01]
[c28a-s2:18522] [ 6] /apps/compilers/gcc/5.2.0/lib64/libstdc++.so.6(+0x8ce18)[0x2b10e0775e18]
[c28a-s2:18522] [ 7] /apps/compilers/gcc/5.2.0/lib64/libstdc++.so.6(+0x8d31c)[0x2b10e077631c]
[c28a-s2:18522] [ 8] sst(_ZNSt6vectorIcSaIcEE17_M_default_appendEm+0x83)[0x45eda3]
[c28a-s2:18522] [ 9] sst(_ZN3SST5Comms9serializeINS_11ConfigGraphEEESt6vectorIcSaIcEERT_+0x10b)[0x45ef5b]
[c28a-s2:18522] [10] sst(_ZN3SST5Comms4sendINS_11ConfigGraphEEEviiRT_+0x1a)[0x45ef9a]
[c28a-s2:18522] [11] sst(main+0x86c)[0x4635fc]
[c28a-s2:18522] [12] /lib64/libc.so.6(__libc_start_main+0xfd)[0x388881ed1d]
[c28a-s2:18522] [13] sst[0x454239]
[c28a-s2:18522] *** End of error message ***
